// client/src/components/ChatWindow.tsx
import MessageBubble from './MessageBubble';
import React from 'react'; 

type Sender = keyof typeof senderLabel;
const senderLabel = {
  monday: '먼데이',
  gaebot: '개봇',
  user: '나'
} as const;

function ChatWindow({ chatLog }: { chatLog: { sender: Sender, message: string }[] }) {
  return (
    <div className="h-[70vh] overflow-y-auto p-4 bg-white rounded shadow mb-4">
      {chatLog.map((msg, idx) => (
        <MessageBubble key={idx} sender={senderLabel[msg.sender]} message={msg.message} />
      ))}
    </div>
  );
}

export default ChatWindow;

// client/src/components/ChatWindow.svelte

<script lang="ts">
  import MessageBubble from './MessageBubble.svelte';
  import type { ChatMessage, Sender } from '$lib/types';

  export let chatLog: ChatMessage[];

  const senderLabel: Record<Sender, string> = {
    monday: '먼데이',
    gaebot: '개봇',
    user: '나'
  };
</script>

<div class="h-[70vh] overflow-y-auto p-4 bg-white rounded shadow mb-4">
  {#each chatLog as msg (msg.id)}
    <MessageBubble sender={msg.sender} senderLabel={senderLabel[msg.sender]} message={msg.message} />
  {/each}
</div>
