// client/src/components/InputBox.tsx
import React from 'react'; 
import { useState } from 'react';

function InputBox({ onSend }: { onSend: (message: string) => void }) {
  const [input, setInput] = useState('');

  const handleSend = () => {
    if (!input.trim()) return;
    onSend(input);
    setInput('');
  };

  return (
    <div className="flex">
      <input
        className="flex-1 border border-gray-300 rounded-l px-3 py-2"
        placeholder="메시지를 입력하세요"
        value={input}
        onChange={(e) => setInput(e.target.value)}
        onKeyDown={(e) => e.key === 'Enter' && handleSend()}
      />
      <button
        className="bg-black text-white px-4 rounded-r"
        onClick={handleSend}
      >
        보내기
      </button>
    </div>
  );
}

export default InputBox;

// client/src/components/InputBox.svelte

<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();
  let input = '';

  function handleSend() {
    const messageToSend = input.trim();
    if (!messageToSend) return;
    input = '';
    dispatch('send', { message: messageToSend });
  }
</script>

<div class="flex">
  <input
    class="flex-1 border border-gray-300 rounded-l px-3 py-2"
    placeholder="메시지를 입력하세요"
    bind:value={input}
    on:keydown={(e) => {
      if (e.key === 'Enter') {
        e.preventDefault();
        handleSend();
      }
    }}
  />
  <button
    class="bg-black text-white px-4 rounded-r"
    on:click={handleSend}
  >
    보내기
  </button>
</div>
